### ISSUE TITLE
Invoke-CMDownloadBIOSPackage.ps1 does not work in older Dell Systems with Axx BIOS

### ISSUE THREAD

**Issue by StephanHeyer** [SCConfigMgr/ConfigMgr#12]
Hi,
first of all, thank you for your outstanding work with modern BIOS and driver management. We really appreciate your work!

We've experienced an issue with the Invoke-CMDownloadBIOSPackage.ps1 script running on older Dell Latitude systems with Axx BIOS version numbers. On these systems, all BIOS packages returned by the Web service matches and therefore the last returned package will be applied. The script errors then out with the returncode 1. I've attached the BIOSPackageDownload.log from a E6430. This happens with the newest version (2.0.0) from the script.
[BIOSPackageDownload.log](https://github.com/SCConfigMgr/ConfigMgr/files/1640099/BIOSPackageDownload.log)

Running the same task sequence on an E7450 with BIOS 1.17.5 works fine and the new BIOS 1.18.5 gets applied.

Thank you for looking at this

Kind regards
Stephan Heyer
Zehnder GmbH

**Comment by viriio** [comment]
I'll give this one a crack. Check line 387 out. I reckon it may be similar to your other issue. #13 

Based on your previous issue with the E6430 it wasn't returning a SystemSKU for that model.

It'd be interesting to know what the PackageDescription is set on one or more of those packages to work out what code is needed. For some reason I'm thinking its blank which would cause them all to return.

Line 387:
`if (($Package.PackageDescription -match $SystemSKU) -and ($ComputerManufacturer -match $Package.PackageManufacturer)) {`

To gather more information, may I suggest you temporary change line 388:

from:
`Write-CMLogEntry -Value "Match found for computer model and manufacturer: $($Package.PackageName) ($($Package.PackageID))" -Severity 1`

to:
`Write-CMLogEntry -Value "Match found for computer model and manufacturer: $($Package.PackageName) ($($Package.PackageID)) PackageDescription: $($Package.PackageDescription)" -Severity 1`

Then post the log file again. Basically trying to capture the PackageDescription.

**Comment by StephanHeyer** [comment]
Hi,
I've changed line 388 and attached the output. Thank you for looking at this.

[BIOSPackageDownload.log](https://github.com/SCConfigMgr/ConfigMgr/files/1642967/BIOSPackageDownload.log)

Kind regards
Stephan

**Comment by StephanHeyer** [comment]
Hi, 
I've tested again with the 30.01.2018 version 2.0.0 of the script and it still can't detect the right package to use:
[BIOSPackageDownload.log](https://github.com/SCConfigMgr/ConfigMgr/files/1685844/BIOSPackageDownload.log)

**Comment by Minutemaiid** [comment]
Hi,

I'm having this same issue.  Dell OptiPlex 9010 without a systemSKU, and so every BIOS package is a match.
Would it make sense to have a fallback to Model match only if the systemSKU is blank?  Any danger in doing that?

I'm running the 2.0.1 version of the Invoke-CMDownloadBIOSPackage.ps1 script, btw (latest as of today).

Thanks for this amazing solution.  When it works, it's one hell of a time saver.

Cheers,
Chris

**Comment by Minutemaiid** [comment]
For what it's worth...

I've made some edits to the Invoke-CMDownloadBIOSPackage.ps1 script around line 391 where it checks for packages that contain the $SystemSKU and Manufacturer... 

I've put in a condition for $SystemSKU to have a value other than "" before running that step, to prevent the matching of SKU with every BIOS package available.
After that I basically copied this code with another IF statement with a condition of $SystemSKU equaling "", but switched things out to find a match for $ComputerModel within the name of the BIOS update packages.   So far so good... but I've only tested against this OptiPlex 9010.   I've got some other models with this same problem I'll test against in the coming days.

I'm curious to hear why this isn't a good idea.

Waiting on my extended hardware inventory to populate the SystemSKU values so I can run some reports against our 101 different model PCs to see how pervasive this problem is with no SystemSKU value available to match against.

Again... awesome solution Maurice & Nickolaj.   Thank you.

**Comment by ekrizon** [comment]
Hi @Minutemaiid .  I am having this issue as well... Would you be willing to provide your complete code until @maurice-daly or @NickolajA look into this?  We have many old Dells.

Thanks in advance.

**Comment by Stuart42** [comment]
We saw a similar problem - I ended up modifying the section around line 380 to fill the $SystemSKU variable with value from BaseBoardProduct if it was empty. Seems to work for us so far.

`		"*Dell*" {
			$ComputerManufacturer = "Dell"
			$ComputerModel = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model
			$SystemSKU = (Get-CIMInstance -ClassName MS_SystemInformation -NameSpace root\WMI).SystemSku
			if ($SystemSKU -eq "")
			{
				$SystemSKU = (Get-CIMInstance -ClassName MS_SystemInformation -NameSpace root\WMI).BaseBoardProduct
			}
		}`
