### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 - Not downloading drivers from Peercache sources

### ISSUE THREAD

**Issue by LukeZee** [SCConfigMgr/ConfigMgr#131]
I am having problems trying to use the ApplyDriverPackage script when content should be sourced from Peercache hosts.  Instead the download for drivers always goes back to an offsite distribution point even though the peer has the files and is showing that the content is there in the config mgr database - all other content for the deployment comes from the peer as expected with the exception of drivers.  Not sure if the script has ever been tested in this type of scenario (OSD from Peercache) any assistance would be appreciated.

**Comment by NickolajA** [comment]
It's simply because we don't store the downloaded driver package in the ConfigMgr client cache, since it's not supported when executed in WinPE:

https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_DownloadPackageContent

Unfortuantely, I'm not able to find a better answer than this.
