### ISSUE TITLE
Bug in Invoke-HPBiosUpdate

### ISSUE THREAD

**Issue by Patrstro** [SCConfigMgr/ConfigMgr#150]
The code sets the path for the password.bin file to where the bios package is located. Causing the script to not be able to autoapply the update without entering the password (can't find to file since its not in the BIOS Packages).
Changed the code similiar to earlier version to point to the password.bin file located with the BIOSUpdate-scripts. 
From:
`
		$FlashSwitches = $FlashSwitches + " -p$($Path)\$($PasswordBin)"	
`
To:
`$FlashSwitches = $FlashSwitches + " -p$($PSScriptRoot)\$($PasswordBin)"	`

Or is this expexted behavior?

**Comment by frank-oelkuch** [comment]
Had to do the same thing.

We are utilizing the Driver Automation Tool to download and create our BIOS Update packages and therefore unwilling to package a password.bin into all of them manuall afterwards.

I found this change especially weird as the version history states that the script would look for the update file within $Path now instead of $PSScriptRoot. However, I did not notice any changes regarding $Path and $PSScriptRoot besides the -p switch.

**Comment by ErikS90** [comment]
Same here- better to stick with 1.0.4.
1.0.5 attempts to use a non-existent password .bin within the BIOS update package rather than the script package, as it should according to "save the password file to the same directory as the script", if you check the HPFlashUtil logs.
