### ISSUE TITLE
_SMSTSPackageID breaks OS lookup when using Standalone Media

### ISSUE THREAD

**Issue by beanska** [SCConfigMgr/ConfigMgr#22]
This may be out of scope but I want to raise the issue for those that may be using standalone media w/ Modern Driver Management. In the case of using standalone media, the variable _SMSTSPackageID is changed from the package id (e.g. ABC000123) to "INMEM_TS". This breaks calling the web service to retrieve the OS version.

As a workaround I am setting the variable "SMSTSPackageID" (No underscore) statically in my TS and then I modified the code slightly. 

>        $TSPackageID = $TSEnvironment.Value("_SMSTSPackageID")
>        if ($TSPackageID -eq 'INMEM_TS') {
>            $TSPackageID = $TSEnvironment.Value("SMSTSPackageID")
>        }

**Comment by Mayanweb** [comment]
I can confirm we are seeing the same issue with standalone media deployments. The 'work around' suggested by @beanska  allows the calling of the web service to work but then the actual download of the drivers fails... @beanska did you get the TS to complete successfully? If so - did you make any other changes?

**Comment by beanska** [comment]
No, I abandoned Modern Driver Management all together.

**Comment by Mayanweb** [comment]
Anyone have any suggestions on how to resolve this?
We are sticking with MoDM but the lack of standalone media support is a problem.
Accept that Bios/Drivers will pulled over the network - just want to avoid having to pull the full customised OS... any pointers/suggestions guys?

**Comment by Mayanweb** [comment]
@psxc2k3  - I am very interested in how you resolved this issue! Can you share here? or PM me at "gt@Mayanweb.com" - I would be very grateful and will submit a pull request once verified.
Many thanks...

**Comment by psxc2k3** [comment]
I've attached two zip-files. They include a modified version of the .ps1 file, and a .diff which holds the changes from the original.
The changes I did wasn't much. A little more for BIOS updates, but mainly because the update program creates a log in the directory where the patch is located.
Since the ID of the task sequence is unknown when using stand-alone media, the parameter "-TSPackageID" needs to Applied along With the other variables in Your task sequence, like the following example:
-URI "http://<servername>/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "<Secret key>" -Filter "Driver" -DeploymentType BareMetal -TSPackageID "<Tasksequence ID>"

The changes done will make the script first search the local media, and if nothing is found will try to download from DP (same as before)

As with anything on the internet - try before you commit! ;)

[Invoke-CMApplyDriverPackage.zip](https://github.com/SCConfigMgr/ConfigMgr/files/2000363/Invoke-CMApplyDriverPackage.zip)
[Invoke-CMDownloadBIOSPackage.zip](https://github.com/SCConfigMgr/ConfigMgr/files/2000364/Invoke-CMDownloadBIOSPackage.zip)

**Comment by psxc2k3** [comment]
My modfication had a small bug - it would fail if one removed the boot media during the process.
I've Attached zip-files With the modified files and the .diff from the original. Sorry.
[Invoke-CMApplyDriverPackage.zip](https://github.com/SCConfigMgr/ConfigMgr/files/2034247/Invoke-CMApplyDriverPackage.zip)
[Invoke-CMDownloadBIOSPackage.zip](https://github.com/SCConfigMgr/ConfigMgr/files/2034248/Invoke-CMDownloadBIOSPackage.zip)
