### ISSUE TITLE
Issue detecting multiple Driver packages

### ISSUE THREAD

**Issue by kevschu2** [SCConfigMgr/ConfigMgr#65]
We deploy 1709 in production and I am starting to roll out 1803 to our pilot users as an in-place upgrade TS.  The issue I am running into is that the script seems to think both the 1709 and 1803 HP driver packages are valid for the 1803 image, and when it tries to decide which one to keep, it removes both of them.  
<img width="373" alt="840g3win10driverpackages" src="https://user-images.githubusercontent.com/26821966/43861864-fd9aa4ea-9b0c-11e8-86be-a9992599d54e.png">

**Comment by dytegry** [comment]
We are also experiencing this issue when installing drivers in a OSD TS, where there are two similar HP models (one touch screen, one without), the script finds two packages, then removes both, stating

"Removing driver package matching SystemSKU but not computer model..."

I've attached the applydriverpackage.log that shows this issue.

[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2282637/ApplyDriverPackage.log)

**Comment by psxc2k3** [comment]
There is a bug in the script (Invoke-CMApplyDriverPackage.ps1) which affects HP/Hewlett-Packard models.
I've added a fix (below). Just replace the lines starting at line 597 With the following:

----- code snip -----
# Process driver package list in reverse
for ($i = ($PackageList.Count-1); $i -ge 0; $i--) {
 $tempPackage = $($PackageList[$i].PackageName -Split(" - ")).Replace($ComputerManufacturer, "").Trim()[1]
 $tempModel = $ComputerModel.Replace("HP ", "")
 Write-CMLogEntry -Value "Matching $tempPackage against $tempModel ..." -Severity 1
 if ($tempPackage -inotmatch $tempModel) {
  Write-CMLogEntry -Value "Removing driver package matching SystemSKU but not computer model: $($PackageList[$i].PackageName)" -Severity 1
  $PackageList.RemoveAt($i)
 }
}
----- end code snip -----

I'm sure the author fixes this in a later version.

**Comment by dytegry** [comment]
Thanks for the suggestion psxc2k3, however we're already running the latest version of the script (2.1).  That said, I did replace the lines the in script that deal with the 'process driver package list in reverse', with what you suggested, however this didn't resolve the issue.

Thanks again for the suggestion though :)

**Comment by NickolajA** [comment]
We did some modifications to this in 2.1.5 that just was released. Please let us know if it works better for these models.

**Comment by Gor3t3x** [comment]
@NickolajA seem to be the hidden part of the iceberg:

840 G5 and 850 G5 share the same SKU.

Package for 1709 or 1803 are the same (same SP pack)

That brings the question, how we handle this? If we download packages for those 2 versions of Windows for those 2 models, that makes 4 packages that "match"

`Driver package list contains 4 matches. Attempting to remove driver packages that do not match the computer model.`

Then it drops the packages who don't match on the model value from wmi

`Removing driver package due to inconsistency between computer model value from WMI 'HP EliteBook 840 G5' and the translated driver package computer model name 'HP EliteBook 850 G5 Notebook PC'`

Then we still have 2 packages that match
 
Do we juste use 1 package with the right SKU for the 2 models of 2 versions of Windows?
then we see:

`An error occurred while applying drivers (multiple package match). Continuing with warning code: 2. See DISM.log for more details	ApplyDriverPackage	26.10.2018 15:21:43	1172 (0x0494)
`

Regards,


gore.
