### ISSUE TITLE
double drivers package for some model

### ISSUE THREAD

**Issue by JoelFrance** [SCConfigMgr/ConfigMgr#66]
Hi
We have with Dell  some model  like
Latitude E6430      package : Drivers - Dell Latitude E6430 - Windows 10 x64
Latitude E6430s    package :  Drivers - Dell Latitude E6430s - Windows 10 x64
or Dell Optiplex 9020  and Dell Optiplex 9020M

For a E6430 , the script Invoke-CMApplyDriverPackage.ps1 find 2 drivers packages (E6430 and E6430s)  and choose the latest one who is not the good one for us ...
The version of the script is 2.1
I need to modify 3 lines  to resolve the problem:  						
                if ($PackageNameComputerModel -match $ComputerModel+" ") 
		if ($Package.PackageDescription -match $SystemSKU+" ") {
                if ($PackageNameComputerModel -match $ComputerModel+" ") {

do you have any others solutions?
thanks

**Comment by vorlon77** [comment]
That issue occurs with all of the models whose name is a part of a
different model name.

Part of the fix is to NOT compare the model name if the SKU matches. The
other part is to use equals with the model name instead of match after
removing the trailing spaces that some model/BIOS versions tack on.

Allan.

**Comment by NickolajA** [comment]
Hi, do you still see this issue with 2.1.4?
