### ISSUE TITLE
systemsku?

### ISSUE THREAD

**Issue by JoelFrance** [SCConfigMgr/ConfigMgr#67]
Hi 
i don't understand why the script use "computer model" and systemsku. 

In some case, systemsku is false  (but not empty) and computer model seems always good  ( model Latitude 7490 and systemsku = 081C in my computer...)

Someone can explain me what is exactly systemsku? and why this script prefer to use systemsku?

Thanks for the information.

**Comment by vorlon77** [comment]
the SystemSKU is what Dell calls systemID.  The interesting thing to note is that Dell doesn't use the model name to match updates because although it works most of the time, it doesn't work ALL of the time.  Besides the naming confusion of the new 2-in-1 models, the oddest examples I've seen are with some of the laptop models such as the Latitude E5250 and Latitude 5250.  There are at least 2 systemID values but both of them have the description of E5250/5250 and so if you try to construct and match on the model name, you aren't going to find it.  This is why the main Driver Automation Tool is unable to find BIOS updates for Models like the Latitude E5550 since it tries to match the model name with the BIOS update and can't find a match.
