### ISSUE TITLE
Certain Drivers Not Applying

### ISSUE THREAD

**Issue by darthsinus** [SCConfigMgr/ConfigMgr#7]
When we use this in an SCCM TS on a Dell Latitude 7480 3 drivers do not apply and the devices show up in device manager as follows:

Display Adapter - Set to Microsoft Basic Display Adapter should be Intel(R) HD Graphics 620 - 
ControlVault Device - set to Broadcom USH Dell should be ControlVault w/o Fingerprint Sensor 
Bluetooth - set to unknown device should be Intel(R) Wireless Bluetooth

When we update the driver manually in device manager and point to the driver pack as the source then the correct driver is installed so the correct driver exists in the package. Every other device seems to apply fine also so the script is working.

**Comment by viriio** [comment]
Any log files?
Which OS?
Which version of the script?
Could be the OS is picking up the rest of the drivers and the script isn't picking up any due to detection error. Note, the script has been updated a few times this year that fixed some detection of models in particular on Dells.

**Comment by darthsinus** [comment]
We've updated the web service to version 1.5.0, re-downloaded the drivers with version 5.1.7 of the Driver Automation Tool and are using version 2.0.1 of the script to apply the drivers bare metal in an OS Deployment task sequence. This time on a Dell Latitude 7280

Now we are seeing the script return empty for driver packs. We checked the driver pack and it has the correct information in the comments (Dell Latitude 7280 Windows 10 x64 Drivers (Models included:079F)) so that it should be identified, downloaded and applied.

ApplyDriverPackage Log Attached: 
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1655706/ApplyDriverPackage.log)

**Comment by NBL-HEIM** [comment]
I also am running the latest scripts, Webservice, and Driver tool and i cannot for the life of me get a Dell XPS 13 9360 to apply its drivers.  I also tried to custom import the driver using the powershell detection:

get-wmiobject -class Win32_ComputerSystem | Select-Object -ExpandProperty Model

and 

(Get-CIMInstance -ClassName MS_SystemInformation -NameSpace root\WMI). SystemSku

based on what these values return and importing them using the custom import job on DAT....still doesnt work.  

Please help

**Comment by darthsinus** [comment]
We have just tried with version 2.0.2 of the script. The driver package is identified correctly and the script attempts to download it, however the step is failing in the task sequence with the SMSTS.log error "Failed to run the action: Dynamically Apply Drivers. Not enough storage is available to complete this operation. (Error: 0000000E; Source: Windows)"

When I inspect the downloaded drivers in the folder that dism is trying to run I can only see audio drivers have been downloaded and the SMSTS.log shows that the script is only attempting to download the content of the audio driver folder within the driver package.
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1664062/ApplyDriverPackage.log)

**Comment by darthsinus** [comment]
We have just run a TS with the script running post sccm client install with the -DeploymentType DriverUpdate parameter and it is still only downloading the audio drivers but it is applying the drivers this time.

It appears that only the Audio folder and its sub folders are being downloaded. we've double checked the package in SCCM and it is pointing to the root (StandardPkg) folder created by the driver automation tool.
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1664202/ApplyDriverPackage.log)

**Comment by NickolajA** [comment]
Have you tried to distribute the package? We've seen that the full source content sometimes doesn't get send correct to the DP. We're investigating this as some kind of timing issue in ConfigMgr. However, I do not recommend using the DriverUpdate method for deploying maching, use the BareMetal method (or don't specify the DeploymentType parameter at all)

**Comment by NBL-HEIM** [comment]
Ok so I've tried the latest scripts and am still unable to get this Dell XPS 13 9360 to apply its drivers.  I also notice that in the ApplyDriverPackage.log file its telling me that the OSImageVersion is 6.1.7601.23807.  I'm deploy Windows 10 v1703 version 10.0.15063.296

So I tried to fool the script in creating a driver package for the Dell XPS 13 9360 using Windows 10 driver but relabeled the package to a Windows7 name.  This still didnt work.  

..At a lost and may go back to using traditional driver management to get this working again on my production environment.

**Comment by NickolajA** [comment]
Do you have a task sequence handling multiple operating system images, like multiple Apply Operating System steps for both Windows 7 and Windows 10. In that case it's not a supported scenario.

**Comment by NickolajA** [comment]
The script reads the OS image build version information for the running task sequence, and returns any of the Apply Operating System steps that it finds (there's no particular order in which it returns, at least not hard-coded).

**Comment by NBL-HEIM** [comment]
@NikolajA

You hit to right on the money!  My task sequence does have multiple Apply OS steps and accommodates both windows 10 and 7.  I did this to simplify the imaging process with our desktop technicians.   

Would there be a way accommodate for this in the script or is it easier to provide 2 task sequences, 1 for each OS

Also, would you happen to have some insights as to why my Dell XPS 13 wont apply its drivers from the DAT tool?  I’m curious as to how the SKU is being applied and how it’s reference in the application package and/or the folder structure.  Is it MIF based?  

Much thanks
Dean

**Comment by NickolajA** [comment]
I've thought about that as well, but not come up with a good way to determine which of the Apply Operating System steps to read the data from without requiring external data passed into the script (a solution that I'm not keen about).

What's the name of the driver package in ConfigMgr and what output do you get from that WMI query where you look for the model on the Dell XPS 13?

**Comment by NBL-HEIM** [comment]
I used the powershell command from this apply driver script on the Dell XPS 13 machine.

get-wmiobject -class Win32_ComputerSystem | Select-Object -ExpandProperty Model

it returns the following: 
XPS 13 9360

(Get-CIMInstance -ClassName MS_SystemInformation -NameSpace root\WMI). SystemSku

returns the following: 
075B 

When I run the DAT tool and download from the dell catalog, it shows the model:  "Dell XPS Notebook 9360".  The .CAB download from this tool is the correct,  I have verified that the DAT tool is downloading the same version as the .CAB specified from the Dell Enterprise CAB website for a Dell XPS 13 9360.   When I choose that model in the DAT tool to make a package with Windows 10, the package name in SCCM is the following: 

"Drivers - Dell XPS Notebook 9360 - Windows 10 x64"

If I rename the package to "Drivers - Dell XPS 13 9360 - Windows 10 x64" to satisfy the WMI query from above, it still wont apply the drivers.  I also tried to recreate the package with a different name "Drivers - Dell XPS 13 9360 - Windows 7 x64" due to the OSImageVersion sometimes pulling 6.1 and calling the machine Windows 7....when in my UDI task sequence, i picked a Windows 10 image.  

still wont apply after all these changes.

**Comment by NBL-HEIM** [comment]
@Nikolaja

I've tried your latest revision of 2.0.4 of this ApplyDriver script and it works on the Dell XPS 13 9360.  it looks like its going off of the SKU instead of the model and associating the 075B to the renamed "Drivers - Dell XPS 13 9360 -Windows 10 x64" driver package.

I will try to recreate the driver package straight from the DAT tool and see if it works without alterations to the package name.

**Comment by NickolajA** [comment]
That sounds great, I'll close the issue. Let us know if you're still experiencing issues.
